SHOW DATABASES;

DROP TABLE IF EXISTS CastedVote;
DROP TABLE IF EXISTS VotingRegistry;
DROP TABLE IF EXISTS offered_at;
DROP TABLE IF EXISTS Ballots;
DROP TABLE IF EXISTS Monitor;
DROP TABLE IF EXISTS Clerk;
DROP TABLE IF EXISTS ElectionsStaff;
DROP TABLE IF EXISTS Center_times;
DROP TABLE IF EXISTS VotingCenter;
DROP TABLE IF EXISTS Folks_email;
DROP TABLE IF EXISTS Folks;
DROP TABLE IF EXISTS Places;

DROP DATABASE IF EXISTS wonderland;
